### PR TITLE
Push to shared app collection

### PR DESCRIPTION
**Pull request by QuentinBisson**

### CODE REVIEW

**Comment by MarcelMue** [comment]
Needs more updates I think - architect-orb is not happy

**Comment by ubergesundheit** [comment]
Rebase this with the changes in #109

**Comment by QuentinBisson** [comment]
Closes https://github.com/giantswarm/config-controller/pull/109

**Comment by QuentinBisson** [comment]
It seems better. Thanks @ubergesundheit

**Review by ubergesundheit — APPROVED** [review]

**Pull request merged**
